_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: None
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  PANOPTIC_DEEPLAB:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True
SOLVER:
  MAX_ITER: 999999
  IMS_PER_BATCH: 2
  LR_SCHEDULER_NAME: "WarmupPolyLR"
INPUT:
  FORMAT: "RGB"
  CROP:
    SIZE: (64, 128)
  IMG_SIZE: [64, 128]  # h, w
DIS_EMBED_HEAD:
  MAX_DISP: 192
  LOSS_TYPE: "panoptic_guided"
  HOURGLASS_LOSS_WEIGHT: [0.5, 0.7, 1.0]
  INTERNAL_LOSS_WEIGHT: [0.5, 0.7, 1.0]   # loss weight for pyramids
  GUIDED_LOSS_WEIGHT: [0.5, 0.7, 1.0]   # guided_smooth, guided_boundary, smooth_L1
  STRESHOLD_GUIDED_LOSS: 10.0    # for the guided_smooth
  REGRESSION_INPLANES: 256  # Discard, now take the maxdisp as the input dimension of 3D-Conv (2D-Conv)
  HOURGLASS_INPLANES: 32    # Discard, now take the maxdisp as the input dimension of hourglass
  HOURGLASS_TYPE: "hourglass_2D"
  RESOL_DISP_ADAPT: False   # weather the maxdisp reduce with the pyramids
  GRADIENT_TYPE: "sobel"
