_BASE_: Base-PanopticDeepLab-OS16.yaml
MODEL:
  WEIGHTS: "./model/model_best.pth"
  PIXEL_MEAN: [107.88465124608473, 102.6064127952325, 93.83097775116936]  #[ 0.485, 0.456, 0.406 ] or [123.675, 116.280, 103.530]
  PIXEL_STD: [49.61812515777384, 45.72323916028775, 42.10830307882334]  #[ 0.229, 0.224, 0.225 ] or [58.395, 57.120, 57.375]
  BACKBONE:
    NAME: "build_resnet_deeplab_backbone"
  RESNETS:
    DEPTH: 50
    NORM: "SyncBN"
    RES5_MULTI_GRID: [1, 2, 4]
    STEM_TYPE: "deeplab"
    STEM_OUT_CHANNELS: 128
    STRIDE_IN_1X1: False
  PANOPTIC_DEEPLAB:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  SEM_SEG_HEAD:
    USE_DEPTHWISE_SEPARABLE_CONV: True
  DIS_EMBED_HEAD:
    MAX_DISP: 192
    LOSS_TYPE: "smoothL1_only"  # "smoothL1_only" or "panoptic_guided" or "l1_norm"
    HOURGLASS_LOSS_WEIGHT: [ 0.5, 0.7, 1.0 ]
    INTERNAL_LOSS_WEIGHT: [ 1.0, 1.0, 1.0 ]   # loss weight for pyramids
    GUIDED_LOSS_WEIGHT: [ 1.0, 1.0, 1.0 ]   # guided_smooth, guided_boundary, smooth_L1
    STRESHOLD_GUIDED_LOSS: 10.0    # for the guided_smooth
    REGRESSION_INPLANES: 192  # to change dimension during the 3D-regression
    HOURGLASS_INPLANES: 192
    HOURGLASS_TYPE: "hourglass_2D"
    RESOL_DISP_ADAPT: False   # weather the maxdisp reduce with the pyramids
    GRADIENT_TYPE: "sobel"
    ZERO_DIS_CONSIDERED: False
    FUSION_MODEL: "multi"  # "multi" or "share"
  MODE:
    PANOPTIC_BRANCH: False
    DISPARITY_BRANCH:  True
    FEATURE_FUSION: False  # whether create cost volume with panoptic features
SOLVER:
  MAX_ITER: 9999999
  IMS_PER_BATCH: 12
  LR_SCHEDULER_NAME: "WarmupPolyLR"  # WarmupCosineLR or WarmupPolyLR
  BASE_LR: 0.001
  FREEZE_BACKBONE: False
  FREEZE_PANOPTIC: True
  FREEZE_DISPARITY: False

  FREEZE_DISPARITY_4: True
  FREEZE_DISPARITY_8: True
  FREEZE_DISPARITY_16: False
  CHECKPOINT_PERIOD: 5000
DATASETS:
  TRAIN: ("kitti_2015_train",)   # sceneflow_driving_train or cityscapes_fine_joint_train or kitti_2015_train or kitti360_train or sceneflow_flying3d_train
  TEST: ("kitti_2015_val",)   # sceneflow_driving_val or cityscapes_fine_joint_train or kitti_2015_val or kitti360_train or sceneflow_flying3d_val
TEST:
  EVAL_PERIOD: 0
  PRECISE_BN:
    ENABLED: False
INPUT:
  FORMAT: "RGB"
  CROP:
    SIZE: (256, 512)
    VAL_SIZE: (256, 512)
    ENABLED: True
    TYPE: "absolute"
  IMG_SIZE: [540,960]  # h, w  540,960 (sceneflow) or 375,1242 (kitti2015) or 1024,2048 (cityscapes) or 376,1408 (kitti360)
  DO_AUGUMENTATION: False
OUTPUT_DIR: "./output"    # the dir for save/read checkpoint and ....
RESUME: False  # If `resume` is True, this method attempts to resume from the last checkpoint, if exists. Otherwise, load checkpoint from the cfg.WEIGHTS.
